TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += $(TOP)/SpellmanHVSup/devSpellmanHV.proto

#=======================================
include $(TOP)/configure/RULES
