version: '3.8'

services:
  minerva_dqm_plots:
    container_name: minerva_dqm_plots
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/nfs/minerva/dqmtest_cpernas/SL7_testing/gmbrowser/plots/:/home/nfs/minerva/dqmtest_cpernas/SL7_testing/gmbrowser/plots/
      - /data/grafana/Mx2/:/data/grafana/Mx2/
      - /home/nfs/minerva/Mx2_monitoring/last_log_entry.txt:/home/nfs/minerva/Mx2_monitoring/last_log_entry.txt
