version: '3.8'

services:
  fastapi-app-prod:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      IP_LOCAL : ${LOCAL_IP}
      INFLUX_PORT: "8086"
    ports:
      - "${LOCAL_IP}:8000:8000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
      
  react-app-prod:
    build:
      context: ./Frontend
    ports:
      - "${LOCAL_IP}:3006:3006"
    environment:
      - REACT_APP_ENV=prod
      - REACT_APP_HOST_IP_ADDRESS=http://${LOCAL_IP}:8000
    volumes:
      - ./Frontend/src:/app/src