version: '3.8'

services:
  fastapi-app-dev:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      IP_LOCAL : ${LOCAL_IP}
      INFLUX_PORT: "8086"
    ports:
      - "${LOCAL_IP}:8001:8000"

  react-app-dev:
    build:
      context: ./Frontend
    ports:
      - "${LOCAL_IP}:3002:3006"
    environment:
      - REACT_APP_ENV=dev
      - REACT_APP_HOST_IP_ADDRESS=http://${LOCAL_IP}:8001
    volumes:
      - ./Frontend/src:/app/src